### ISSUE TITLE
Release 1.0.0-beta4

### ISSUE THREAD

**Issue by burningalchemist** [amimof/node-cert-exporter#26] opened 2020-02-10 10:57 UTC
Hi @amimof ,

If you have time, could you please add `1.0.0-beta4` tag, as we have hostname in metrics now and also a bugfix for a certificate version representation since `1.0.0-beta3`.

Kind regards,
Sergei

**Comment by amimof** [comment] 2020-02-10 18:39
Hi @burningalchemist 

I've been doing some thinking and I realised that the hostname label which you helped introduce in https://github.com/amimof/node-cert-exporter/pull/25 will only return the hostname of the Pod (if run in a container). So my plan is to also add a Kubernetes specific label which will return the name of the node. I believe that was the desired behaviour from the beginning.

**Comment by burningalchemist** [comment] 2020-02-10 19:33
Hi @amimof,

Yeah, exactly today I bumped into the same issue. It seems to only work as expected if deployed as a native service and not as a container. I was able to get desired behaviour with Prometheus `relabel_config`, but your plan also makes sense! 👍

**Comment by amimof** [comment] 2020-02-10 19:46
@burningalchemist Yes we have also been using a `relabel_config` for our clusters. I believe it should be possible to retrieve the node name from an env var from within a pod. For example `os.Getenv("NODE_NAME")`.

**Comment by alexmirkhaydarov** [comment] 2020-02-11 23:48
@amimof 
@burningalchemist 

I've created a [PR](https://github.com/amimof/node-cert-exporter/issues/26) implementing the expected behaviour for retrieving the Nodename. Please let me know if looks alright. :)

**Comment by burningalchemist** [comment] 2020-02-12 08:13
@alexmirkhaydarov it looks fine, but it also makes us unable to use it out of Kubernetes, thus making it less generic.

Currently, Kubernetes nodeName label can be added with Prometheus, or correctly retrieved if `hostNetwork: true` is set, but to run it natively with nodeName only, we would need to have NODE_NAME env set on a host manually, which doesn't make sense.

It's up to @amimof, but I would not consider removing hostname completely, but rather having it as a separate label, or actually implementing a fallback to os.Hostname if NODE_NAME can't be found. I'd try the latter.

**Comment by amimof** [comment] 2020-02-12 10:45
@alexmirkhaydarov I don't believe that the hostname label is to be replaced. It has its uses as well as the node name. I haven't had this confirmed, but doesn't Kubernetes add default environment variables to pods such as the node name?

**Comment by burningalchemist** [comment] 2020-02-12 11:11
@amimof Unfortunately not. All the environment variables get injected based upon data available in manifests. Some of the fields are mandatory for manifests, so it makes them look default.

**Comment by alexmirkhaydarov** [comment] 2020-02-12 11:19
@burningalchemist Yes you're right. I've picked up at some-point it won't be useable outside of Kubernetes and so I was working on a fallback fix. But I think having as a separate label makes total sense :)

@amimof
Should we agree to use Nodename as a separate label or use `os.Hostname` as a fallback?

**Comment by amimof** [comment] 2020-02-12 13:45
@burningalchemist 
@alexmirkhaydarov 
Yes node name as a separate label. So it would be up to the admin to set env var using downward api or relabel config in Prometheus since there are no other reasonable solution.

**Comment by alexmirkhaydarov** [comment] 2020-02-12 14:36
@amimof I've updated the original [PR](https://github.com/amimof/node-cert-exporter/pull/27) to include the additional Nodename label.
Removed [change](https://github.com/amimof/node-cert-exporter/pull/27/commits/193d52c8bd45a7aebd5574a8c6fef6ca6d0668bb) based on your comment about it being set by the Admin. :smile:

**Comment by amimof** [comment] 2020-02-12 18:33
@alexmirkhaydarov Thanks. I didn't meant for you to remove the Downward API config in the deploy manifest. What I meant was that the admin is in control of *theis* config. But may use the provided one from this repo which contains necessary config to include node name as an env var.

**Comment by alexmirkhaydarov** [comment] 2020-02-12 19:50
The removal of the downward API back has been reverted on the deploy manifest. This issue can be closed now as the PR has been merged with the necessary changes.

**Comment by amimof** [comment] 2020-02-12 19:51
Just released [v1.0.0-beta.4](https://github.com/amimof/node-cert-exporter/releases/tag/1.0.0-beta.4). Thank you so much for your time and effort 👏

**Closed by amimof** 2020-02-12 19:51 UTC
